Import('BaseEnv')
env = BaseEnv.Clone()

env.Program(target='dungeon', 
            source=Glob('*.cpp'),
            CPPPATH=['#/libmaze'],
            LIBS=['maze', 'ncurses', 'boost_system', 'boost_thread'],
            LIBPATH=['/usr/lib', '#/libmaze'],
            CCFLAGS='-W -Wall -Wextra -Werror -Wno-unused-parameter -g -O3 -std=c++0x')
